# Generated by Django 5.0 on 2024-02-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('guest_count', models.IntegerField()),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Business Meet', 'Business Meet'), ('Anniversary', 'Anniversary'), ('Casual/Other', 'Casual/Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
